package com.torontoOrg.contrack.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;


@Entity
@Table(name = "ContractItems")
public class ContractItem {

    //autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @Column(name = "item")
    private String item;

    @Column(name = "description", length = 2000) // Assuming a longer description
    private String description;

    @Column(name = "location")
    private String location;

    @Column(name = "day_total")
    private Integer dayTotal;

    @Column(name = "total_to_date")
    private Integer totalToDate;


    @CreationTimestamp
    @Column(name = "added_date", updatable = false, nullable = false)
    private LocalDateTime addedDate;

    // Constructors, getters, setters, etc.



    public ContractItem() {
    }

    public ContractItem(int id, String item, String description, String location, Integer dayTotal, Integer totalToDate) {
        this.id = id;
        this.item = item;
        this.description = description;
        this.location = location;
        this.dayTotal = dayTotal;
        this.totalToDate = totalToDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Integer getDayTotal() {
        return dayTotal;
    }

    public void setDayTotal(Integer dayTotal) {
        this.dayTotal = dayTotal;
    }

    public Integer getTotalToDate() {
        return totalToDate;
    }

    public void setTotalToDate(Integer totalToDate) {
        this.totalToDate = totalToDate;
    }

    public LocalDateTime getAddedDate() {
        return addedDate;
    }

    public void setAddedDate(LocalDateTime addedDate) {
        this.addedDate = addedDate;
    }
}
