package com.torontoOrg.contrack.entity;

import javax.persistence.*;

import com.torontoOrg.contrack.entity.enums.ContractItemUnits;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;


@Entity
@Table(name = "ContractItems")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ContractItem {

    //autogenerated id
    //to do : add UUID for id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @Column(name = "itemId", nullable = false)
    private int itemId;

    @Column(name = "item")
    private String item;

    @Column(name = "description")
    private String description;

    @Column(name = "location")
    private String location;

    @Enumerated(EnumType.STRING)
    //default value is "M"
    @Column(
            name = "trackingUnit",
            columnDefinition = "varchar(255) default 'M'")
    private ContractItemUnits trackingUnit;

    @Column(name = "dayTotal")
    private Double dayTotal;

    @Column(name = "totalToDate")
    private Double totalToDate;

    @Column(name = "addedDate")
    private LocalDateTime addedDate;

    @Column(name = "updatedDate")
    @CreationTimestamp
    private LocalDateTime updatedDate;

}
